### ISSUE TITLE
KDE/SDDM does not correctly handle cue with pam_u2f

### ISSUE THREAD

**Issue by Zer0CoolX** [authselect/authselect#179]
Fedora 30 KDE
Yubikey 5 NFC (via USB)
Physical Laptop

**Setup**
Fresh install of Fedora 30 KDE.
- `dnf update`
- reboot
- `dnf install pam-u2f pamu2fcfg`
- `mkdir ~/.config/Yubico` (for user and root at /root)
- `pamu2fcfg > ~/.config/Yubico/u2f_keys` (for user and root at /root)
- `auth select sssd with-pam-u2f-2fa`
- reboot

This results in SDDM (KDE login screen) prompting for credentials and after entering them the button on the Yubikey blinks to indicate to press it. After pressing it nothing happens and light/button eventually turns off. No message about incorrect credentials/failed login, password field can be modified but it will not progress beyond the login page.

I used a LiveCD to comment out the `auth required pam_u2f.so` lines from `system-auth` and `password-auth` in `/etc/authselect` which allowed me to boot up and login without the Yubikey for 2FA.

**Cause**
`authselect` makes the line in the `system-auth` and `password-auth` for u2f as follows:

`auth required pam_u2f.so cue nouserok`

The problem seems to be the `cue` parameter. As far as I am aware SDDM/KDE does not support this, so when trying to login the `cue` parameter attempts to cue the user but fails preventing the login from finishing. When manually removed, all logins seem to work that I tested (login, lock, sudo, su and credential prompts in KDE GUI).

**Problem**
When the cue line is removed logins using U2F 2FA work, but in the places being cued is supported, there is no cue (sudo and su).

**Final Thoughts**
Hopefully this is the right place to post this. I am not sure what can be done to fix this (if there is any interest in fixing it) but wanted to make someone aware.

I have resorted to manually modifying individual files in `/etc/pam.d` to accommodate using the Yubikey for U2F 2FA and prompting only for sudo/su.

Thanks

**Comment by pbrezina** [comment]
Hi, thank you for reporting the issue. This sounds like either KDE or pam_u2f problem. Please try to report it on Fedora [bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora).

**Comment by Zer0CoolX** [comment]
I appreciate the response, however I would not characterize this as a KDE or pam_u2f problem. I would certainly say that the lack of support for `cue` in KDE/SDDM is their fault. I am pretty confident they are are aware of the matter which is how I initially became aware of it.

To me, for what its worth, it seems this is something that authselect should consider in its execution...being the matter of what DE is actually in use and any unique configuration the specific DE requires for 2FA (specifically U2F 2FA as I have tested it). As it stands, it looks like authselect assumes the user is using Gnome.

As described, I can and have configured this manually, with alterations to how authselect might apply very similar settings. pam_u2f, KDE, SDDM, etc. all work without issue when setup manually, if you ignore the fact that GUI authentication does not prompt for the 2FA U2F input/button press outside of having the button blink as the `cue` parameter is not used/supported.

I do not intend to self-promote here, but should you or others be interested in approaching the matter I do have the manual steps I took posted in a repo of mine if that would be helpful to start working it out.

In any case, Thank you for your time!

**Comment by pbrezina** [comment]
> I appreciate the response, however I would not characterize this as a KDE or pam_u2f problem. I would certainly say that the lack of support for cue in KDE/SDDM is their fault.

Using `cue` parameter makes pam_u2f use PAM conversation function to display information to the user. If this breaks authentication, I'd consider it a bug (even a critical bug) in the caller (in this case KDE) and other modules are probably affected too.

So it is either a bug in KDE that it does not support this kind of conversation or it is a bug in pam_u2f that it does something wrong which makes KDE fail.

> I am pretty confident they are are aware of the matter which is how I initially became aware of it.

What do you mean "they are aware". Is there any documentation?

> To me, for what its worth, it seems this is something that authselect should consider in its execution...being the matter of what DE is actually in use and any unique configuration the specific DE requires for 2FA (specifically U2F 2FA as I have tested it). As it stands, it looks like authselect assumes the user is using Gnome.

Yes, authselect upstream currently assumes Fedora and Gnome. When issues arise with different desktop environments, we will certainly try to deal with it as best as we can. However, keep in mind that PAM configuration is system wide, does not apply only to GUI and each user can use different desktop. Ability to apply different configuration to different desktops depends on whether the environments use different PAM service.

> I do not intend to self-promote here, but should you or others be interested in approaching the matter I do have the manual steps I took posted in a repo of mine if that would be helpful to start working it out.

Sure, forward me any information that you have.

**Comment by Zer0CoolX** [comment]
Here is the link to how I do this manually. https://github.com/Zer0CoolX/Fedora-KDE-Yubikey-U2F-2FA-Logins-Guide

As for multiple user environments with multiple DE's, your certainly right. That absolutely sounds like a case in which each DE should strive for a standard way of handling PAM. I had not considered that scenario.

Here is a bug report to SDDM from Nov 2018 #1103 regarding use of cue failing. https://github.com/sddm/sddm/issues/1103. There are other mentions of it elsewhere like reddit and I want to say they have another bug, maybe closed, that had some responses but not solution I just cant dig up at this time. I also vaguely recall seeing a note in Arch wiki about cue not being supported by SDDM/KDE but cant find it.

In any case, my 2 cents, maybe its worthwhile adding something like a -kde switch to authselect which follows configuration similar to my approach vs leveraging the system-auth and password-auth files and having everything else include/substack them. Maybe thats not feasible, and I certainly understand if not.

I am just not holding my breath for KDE to fix this issue themselves. I would imagine it is of very low importance to them considering the volume of issues they must receive. However, it seemed like something that authselect may be able to work around.

Thanks so much for your time and consideration.

**Comment by pbrezina** [comment]
I will check how it handles PAM and let you know.

**Comment by pbrezina** [comment]
I'm sorry, I did not have any time to pursue this so far. Has the situation changed in any way?

**Comment by Zer0CoolX** [comment]
Not as far as I am aware but I have not looked into it much since we discussed it.

**Comment by pbrezina** [comment]
I'm sorry, I didn't have time to investigate this further and unfortunately it is unlikely that I will do it in near future since it is low priority for me. Authselect is using pam_u2f recommended configuration and it works well in Gnome. Please open a bug either against KDE or pam_u2f and reopen it here if there is any change required in authselect.

I'm sorry that I kept you waiting for so long time and for any inconvenience this has caused you.
