### ISSUE TITLE
RFE: pam_env session module

### ISSUE THREAD

**Issue by jamescassell** [authselect/authselect#206]
I've opened a PR for this feature at #205 , but figured I'd open the equivalent ticket requesting the enhancement, since there's been no movement on the PR.

Quoting what I said there:

> pam_env is useful for setting environment variables for all pam
> sessions. Among other things, this can be used to set http_proxy
> environment variables on a system-wide basis to allow normal networking
> functionality on networks that can access the internet only via a proxy.
> 
> The existing pam_env in the auth section does not have any effect for
> pam sessions that bypass the auth modules, such as cached sudo and
> publickey SSH login.
> 
> with-session-pam-env enables the pam_env session module in addition to
> the always-enabled auth module. This makes /etc/security/pam_env.conf
> settings also take effect for public-key-authenticated SSH and cached
> sudo.

**Comment by pbrezina** [comment]
Closing, since calling `pam_env` twice may have unexpected results. The applications that don't call  `pam_authenticate` should at least call `pam_setcred` which will call `pam_env` from `auth`. See comments in the PR. #205
