### ISSUE TITLE
Fingerprint auth should not be enabled for sudo

### ISSUE THREAD

**Issue by benzea** [authselect/authselect#207]
Fingerprint auth really doesn't make any sense for sudo (it is pretty harmful there). I doubt it should be enabled for anything but graphical logins.

**Comment by jamescassell** [comment]
I've definitely used it for sudo. Much better than `NOPASSWD:`, PITA to type password for sudo.

**Comment by benzea** [comment]
It is a **bad** idea. It completely breaks e.g. remoting in through ssh and it also doesn't really proof as much as a password does.

**Comment by benzea** [comment]
See https://gitlab.freedesktop.org/libfprint/fprintd/-/issues/32

**Comment by jamescassell** [comment]
Seems like we need a pam module to detect local console auth vs remote

**Comment by pbrezina** [comment]
@benzea Do you use fprintd for other services? Or you don't use it at all?

**Comment by benzea** [comment]
I don't use fingerprint authentication at all ;-)

But, if I used it, I would expect it to only work from my graphical session. And, really, I would want policy to only allow unlock if other conditions are met.

**Comment by pbrezina** [comment]
@benzea You can call `authselect disable-feature with-fingerprint` to remove the fingerprint module, but I suppose you already know this.

I discussed this with @t8m and it looks like best option will be to modify `fprintd` to add a check for presence of `SSH_*` environments variables. I need to check if sudo won't remove this during pam authentication though.

**Comment by hadess** [comment]
> It is a **bad** idea. It completely breaks e.g. remoting in through ssh and it also doesn't really proof as much as a password does.

That's already fixed, we check for local systemd sessions since the sd-bus port.

**Comment by pbrezina** [comment]
Sweet! @hadess  Is it already released?

**Comment by hadess** [comment]
Since January this year. It's in Fedora 32 now.

**Comment by pbrezina** [comment]
Thank you. Therefore I'm inclining to close this thread since for me the issue was that sudo is delayed by fingerprint on ssh sessions.

@benzea If you feel that sudo-fingerprint support should be optional with fingerprint enabled, can you please open a thread on fedora-devel and see what the community has to say about it?
