### ISSUE TITLE
incorrect handling of multiple conditionals on one line

### ISSUE THREAD

**Issue by lordlimecat** [authselect/authselect#218]
Tested on CentOS 8.2 with shipped version of authselect (1.1.2)

Consider the following pam template (line numbers included for reference):
```
1 auth   {if "with-2fa":requisite|sufficient}   pam_fprintd.so               {include if "with-fingerprint"}
2 auth   sufficient                             pam_u2f.so cue               {include if "with-pam-u2f"}
3 auth   [default=1 ignore=ignore success=ok]   pam_succeed_if.so uid >= 1000 quiet
```

If you have options “with-2fa” and “with-fingerprint” enabled, you will get the following pam file:
```
auth   requisite                              pam_fprintd.so 
auth   [default=1 ignore=ignore success=ok]   pam_succeed_if.so uid >= 1000 quiet
```

However, if you only have “with-2fa” enabled, you will end up with a garbled line:
`auth   requisiteauth   [default=1 ignore=ignore success=ok]   pam_succeed_if.so uid >= 1000 quiet`

In this situation line 3 gets appended right onto the end of line 1. That’s because the “with-2fa” clause of the keyword conditional forces the generation of auth requisite, but the “with-fingerprint” conditional at the end of line 1 prevents the inclusion of the remainder of the line-- including the line break.

PAM will then throw errors when it encounters the generated line, indicating that it cannot parse requisiteauth, and that it cannot find pam module `default=1 ignore=ignore success=ok` in the pam module directory.

This behavior is inconsistent with the language in the man pages for authselect-profiles, which indicates that an `{include if "feature"}` clause should cause the entire line to be included or excluded, rather than just part of the line.

The use-case for something like line 1 above would be to allow using multiple flags to determine whether a single factor is sufficient or requisite when a 2-factor flag is set. The same thing can be accomplished with multiple lines using different "include if"conditions, but requires a more complex configuration.

**Comment by pbrezina** [comment]
Thank you. PR: https://github.com/authselect/authselect/pull/219

**Comment by pbrezina** [comment]
* `master`
  * 4b913748e413314b69c315c314c3d07e10471712
