### ISSUE TITLE
Add systemd-resolved support

### ISSUE THREAD

**Issue by pbrezina** [authselect/authselect#221]
Resolved is now enabled by default since Fedora 33.

See: https://fedoraproject.org/wiki/Changes/systemd-resolved

**Comment by pbrezina** [comment]
* `master`
  * eb4ef2c111b3b439bda66cc0ac8764343e9d6d6f - profiles: add support for resolved

**Comment by pbrezina** [comment]
* `master`
  * c5294c508a940291440eb32d5d750f33baf1ae54 - profiles: add support for resolved

**Comment by imsedgar** [comment]
Question: Why is resolved not neccessary / enabled for profile sssd?
