### ISSUE TITLE
Remove umask option from pam_oddjodb_mkhomedir.so line

### ISSUE THREAD

**Issue by abbra** [authselect/authselect#223]
`pam_oddjob_mkhomedir.so` does not support any PAM option, this is documented in the man page. Authselect specifies `umask` option which is no-op.

```
# fgrep mkhomedir /usr/share/authselect/default/sssd/system-auth
session     optional                                     pam_oddjob_mkhomedir.so umask=0077                    {include if "with-mkhomedir"}
```

`pam_oddjob_mkhomedir.so` relies on `/etc/login.defs` to pick up umask value. Right now it only supports `UMASK` but with https://pagure.io/oddjob/pull-request/12 it will also handle `HOME_MODE` variable. However, PAM module option is not usable and can actually put people into false thinking that it does define something.

**Comment by pbrezina** [comment]
Thank you. I think this is a relic from pam_mkhomedir which has this option.

**Comment by pbrezina** [comment]
* `master`
  * 9f9738737638e3cceb33659ab3e81e59dfb0b83c - profiles: remove umask argument from pam_oddjob_mkhomedir
