### ISSUE TITLE
Need to add pam service name for plasma screen locker

### ISSUE THREAD

**Issue by opoplawski** [authselect/authselect#234]
The KDE 5/Plasma desktop uses the pam service name of "kde" for the screen lock.  I think this just need to be added to https://github.com/authselect/authselect/blob/master/profiles/sssd/system-auth#L5 but I'm not sure.

**Comment by pbrezina** [comment]
Hi, can you please explain the issue in more detail?

**Comment by opoplawski** [comment]
It appears that we must maintain a list of smartcard capable services on that line.  For those services we continue to the "pam_sss.so require_cert" line, otherwise we continue with normal authentication.  With the KDE Plasma desktop, the PAM service name is now "kde" instead of the older "kscreensaver":
```
Apr 16 10:05:16 kcheckpass[7887]: pam_sss(kde:auth): authentication success; logname=USER uid=XXX euid=XXX tty=:0 ruser= rhost= user=USER
```
so we need to add "kde" to that line.
