### ISSUE TITLE
Please add to authselect-migration how to migrate `authconfig --enableshadow --passalgo=sha512` 

### ISSUE THREAD

**Issue by jkonecny12** [authselect/authselect#246]
As far as I know, this command is frequently in the older kickstart files and it's hard (at least for me) to find out how to replace that by the authselect. At the end, I asked the developer of the authselect to find that out. Could you please add what is the recommended replacement of

```
authconfig --enableshadow --passalgo=sha512
```

for the authselect command?

**Comment by pbrezina** [comment]
@jkonecny12 please review https://github.com/authselect/authselect/pull/249

**Comment by jkonecny12** [comment]
Review is there. Thanks for implementing this so quickly!
