### ISSUE TITLE
authselect needs a --version flag

### ISSUE THREAD

**Issue by richiedaze** [authselect/authselect#287]
Please consider adding a version flag to the list of terminal arguments.

**Comment by pbrezina** [comment]
Since 1.3.0, there is undocumented `version` command, i.e. `authselect version`. However, users should use information from their packaging system (e.g. `rpm -q authselect`). Why do you need it?

**Comment by richiedaze** [comment]
I have a custom profile modified for systemd-homed. I would also like to benefit from the changes you make upstream to remodify the templates with scripts using the flag. I found the commit after posting this issue, because silverblue is not on current release.
