### ISSUE TITLE
login does not work with with-pam-u2f 

### ISSUE THREAD

**Issue by alfonz19** [authselect/authselect#290]
Fresh new fedora 35, kde spin. Everything works. I ran

`authselect enable-feature with-pam-u2f`

and finished the token registration:

pamu2fcfg -u mmucha > ~/.config/Yubico/u2f_keys

 Tested via `sudo ls`, prompted to touch device, it works. Then I rebooted to find out, that I cannot login into system. If I enter password, I'm asked to touch the device, after it freezes. If I press the enter with 'empty password', I'm again prompted to touch the device, after which it freezes. Command `journalctl` says that it cannot find password for user - well, if this is related:

```
led 15 21:26:05 fedora sddm[1430]: Authentication information: "Please touch the device."
led 15 21:26:10 fedora sddm-helper[1459]: gkr-pam: no password is available for user
led 15 21:26:10 fedora sddm-helper[1459]: pam_kwallet5(sddm:auth): pam_kwallet5: pam_sm_authenticate
led 15 21:26:10 fedora sddm-helper[1459]: pam_kwallet5(sddm:auth): pam_kwallet5: Couldn't get password (it is empty)
led 15 21:26:16 fedora systemd[1]: fprintd.service: Deactivated successfully.
```

Stopped sddm, disabled feature, started sddm, can login again.
Not sure if this is valid, I moved to kde from cinnamon, but this used to work before.

Also I'm not sure why I'm asked for touch, if I provided password. Is this to be expected? How can I configure it if it is?

**Comment by pbrezina** [comment]
Hi, do you have the opportunity to test the same configuration on gnome/cinnamon?

**Comment by pbrezina** [comment]
Also, can you try to remove `cue` from pam_u2f parameters in /etc/authselect/system-auth as a potential workaround?

**Comment by alfonz19** [comment]
Hi, I will test it for you asap. I can say that it works in fedora33. I cannot verify that 'cue' parameter for you in f35 kde, because the kde was too buggy for me and no forum activity on any issue, so I reinstalled it back to my recent favorite (and after kde fail again my favorite) cinnamon distro. But f35 is probably haunted, so after `dnf update` cinnammon crashes upon login, and I have to figure that one first. I'll be in touch.

**Comment by alfonz19** [comment]
yes, cinnamon works OK for my usecase, which is mostly only login and sudo with pam_u2f.

I'd guess that kde keyring sw (is it called wallet? not sure now) has problem with passwordless login, and instead of using dialog box they cope with missing password via crashing the whole environment...

**Comment by pbrezina** [comment]
I don't see anything we can do from authselect side. Please, report a bug against KDE.

**Comment by alfonz19** [comment]
got it, sorry for wrong report. At first I didn't know what is wrong(and I'm still not sure if my guessed explanation is correct), and wanted to let you know about this. I ditched KDE for their lack of support, so I'm good ;) and I'm not sure if anyone actually reads forums/reports ...

Thanks for you time!

**Comment by pbrezina** [comment]
You can try to report it on [Red Hat bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora) if other channels failed.
