### ISSUE TITLE
po: uk -> ua ?!

### ISSUE THREAD

**Issue by mikhailnov** [authselect/authselect#296]
Seems that uk (Unighted Kingdom) localization is confused with UA (Ukrainian)
https://github.com/authselect/authselect/blob/master/src/man/po/authselect-migration.7.adoc.uk.po

CC @yurchor

**Comment by mikhailnov** [comment]
Hm, seems that it is me who confused it. Closing. Sorry.

**Comment by yurchor** [comment]
No. "uk" is the language code (ISO 639-1) for Ukrainian. The British locale is en_GB. :)

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
