### ISSUE TITLE
Adding optional profile for homed support

### ISSUE THREAD

**Issue by alexpattyn** [authselect/authselect#310]
Based on the discussion [here](https://bugzilla.redhat.com/show_bug.cgi?id=1806949), in order to have fedora support homed without manual changes to `/etc/authselect/system-auth` or `/etc/authselect/password-auth` (which gets overridden on updates) there should be additional optional PAM configs that allow login when systemd-homed is enabled. 

Currently I found that modifying the aforementioned configs allows for login to homed users via `su $USER` and from the gnome login screen. Therefore should I make a new profile that changes those file to enable homed support?

**Comment by alexpattyn** [comment]
Seems like it should be enough to just edit `/etc/authselect/system-auth` and `/etc/authselect/password-auth`. Example config below:

```
# Generated by authselect on Fri Jun  3 13:04:59 2022
# Do not modify this file manually, use authselect instead. Any user changes will be overwritten.
# You can stop authselect from managing your configuration by calling 'authselect opt-out'.
# See authselect(8) for more details.

-auth       sufficient                                   pam_systemd_home.so {include if "with-homed"}
...

-account    sufficient                                    pam_systemd_home.so {include if "with-homed"}
...

-password    sufficient                                  pam_systemd_home.so {include if "with-homed"}
...

-session    optional                                    pam_systemd_home.so {include if "with-homed"}
...
```

**Comment by freddyw** [comment]
I would very much love to see this become a reality. I currently use a 'custom' authselect profile (based on 'minimal')  for this reason but a simple option to enable it in the default profile would be better in many ways i reckon.

**Comment by richiedaze** [comment]
I've been using [mines](https://github.com/richiedaze/authselect/commit/c79b85e1d327a7081ba6b8caf3e1f29b0f105eb7) since Silverblue 32. I haven't updated it since. Feel free to help us all.

**Comment by pbrezina** [comment]
Yes, thank you.
