### ISSUE TITLE
[RFE] optional support for pam_ssh_agent_auth

### ISSUE THREAD

**Issue by jcpunk** [authselect/authselect#312]
pam_ssh_agent_auth seems to be the recommended method for authenticating to sudo remotely using smart cards. (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/managing_smart_card_authentication/index#assembly_authenticating-to-sudo-remotely-using-smart-cards_managing-smart-card-authentication)

Can support for this be added to authselect so I can enable this as needed?

**Comment by jcpunk** [comment]
My primary target is really to require MFA for privileged actions.  I've got a bunch of yubikeys on site and was hopeful to use those for an extra layer of assurance.  Eventually pkinit is on the horizon for MFA kerberos, but we're not there yet.

Letting everything authenticate via the ssh-agent socket is probably a bad idea, but I honestly don't know enough about it to be sure.

**Comment by Jakuje** [comment]
The `pam_ssh_agent_auth` is useful only for the privilege escalation using sudo. Authselect handles only the generic `system-auth` pam stack, which is used mostly for local and remote login. Given that the authselect does not handle the `sudo` stack, I think it should not be part of the `authselect`.

This means, the configuration needs to happen through some other mean than `authselect`, probably ansible or your other favorite configuration management tool

**Comment by jcpunk** [comment]
Sounds like this is out of scope for `authselect`.
