### ISSUE TITLE
Support SOURCE_DATE_EPOCH for artifacts

### ISSUE THREAD

**Issue by Foxboron** [authselect/authselect#319]
`SOURCE_DATE_EPOCH` allows one to preset the timstamp that should be included in build artifacts.

https://reproducible-builds.org/docs/source-date-epoch/
https://reproducible-builds.org/specs/source-date-epoch/

Currently the files generated by `authselect` makes Fedora distribution images unreproducible.

**Comment by pbrezina** [comment]
What is the purpose? Are you willing to submit a PR?

**Comment by Foxboron** [comment]
The purpose is to ensure that any artifacts created by authselect is reproducible at different points in time. If you try to recreate a container image of Fedora/RHEL from 3 days ago, `authselect` would still embed the current time.

I sadly don't know C very well, so I'm not sure if I'm completely the correct person for it. There is an example codesnippet for this in the Reproducible Builds webpage.

**Comment by pbrezina** [comment]
And what precisely do you mean by artifacts? The files that authselect generates? Or built binary?

**Comment by Foxboron** [comment]
Ah, I realized how unprecise I was with the issue. Sorry.

I mean the configuration files authselect generate, yes. The goal is to have Fedora installations from `mkosi` reproducible and the embedded timestamps in the files are one of the issues.

**Comment by pbrezina** [comment]
Ok, so authselect should ready SOURCE_DATE_EPOCH and if set then set this time as "time created" on the files instead of current time?

**Comment by Foxboron** [comment]
Yep :) Exactly.

**Comment by pbrezina** [comment]
Hi, I would like to finally move on and start working on this ticket. Can you give me any guidance on how to implement this on autoconf/automake project?

**Comment by Foxboron** [comment]
Hi!


There are examples for autoconf/automake along with C examples here:

https://reproducible-builds.org/docs/source-date-epoch/

Generally for `authselect` i believe you need to make sure to try look for `SOURCE_DATE_EPOCH` before the two `strfdate` calls in the code.

https://github.com/authselect/authselect/blob/bd90a1503196c4f9b9646c90d5d8174b0e98b33c/src/lib/authselect_backup.c#L82

https://github.com/authselect/authselect/blob/bd90a1503196c4f9b9646c90d5d8174b0e98b33c/src/cli/main.c#L865
