### ISSUE TITLE
New authselect nsswitch plugin support for GNS

### ISSUE THREAD

**Issue by schanzen** [authselect/authselect#324]
Hello,

for the fedora gnunet package [1][2] the installation of the GNU Name System [3] NSSwitch module [4] has changed with newer versions as mentioned here [5].
I have not yet dug into what exactly needs to be changed in the SPEC file apart from running authselect with the plugin, but the page states that

```
To request inclusion of a new nsswitch or PAM module in default authselect profiles, either open an issue on authselect GitHub project or open a bug against authselect component in Fedora bugzilla.
```

feel free to redirect me if I am wrong here.

BR

[1] https://bugzilla.redhat.com/show_bug.cgi?id=2094246
[2] https://copr.fedorainfracloud.org/
[3] https://datatracker.ietf.org/doc/draft-schanzen-gns/, https://www.gnunet.org/gns
[4] https://docs.gnunet.org/installing.html?highlight=nsswitch#nss-plugin-optional
[5] https://fedoraproject.org/wiki/Changes/Make_Authselect_Mandatory#Remove_user-nsswitch.conf_functionality

**Comment by schanzen** [comment]
Not that it seems to me that service name resolution should now happen through systemd-resolvd, but it does not seem to be possible to add plugins to that component easily https://github.com/systemd/systemd/issues/24532.
So I understand that authselect is meant for selection of authentication subsystems, but since it "squats" on nsswitch.conf in general, the option to allow configuration of service name resolvers is now missing/moved to systemd.

**Comment by pbrezina** [comment]
I watched some presentation on the topic and it seems interesting. Is it backwards compatible with DNS?

Yes, we can include a switch to enable gns on desire. But I wonder, since it is not yet even packaged in Fedora, is this something used by common users? Even the copr packages don't have much downloads.

**Comment by schanzen** [comment]
Thanks for the quick reply

> I watched some presentation on the topic and it seems interesting. Is it backwards compatible with DNS?

To a significant degree (but it depends on what you mean by that ;)

> 
> Yes, we can include a switch to enable gns on desire. But I wonder, since it is not yet even packaged in Fedora, is this something used by common users? Even the copr packages don't have much downloads.

Well this is more or less pre-emptively. I have opened a packaging request as you can see and there is the option of just not doing that integration for the first package. Otherwise, there will be a chicken-egg situation (not packaged -> no change in authselect, no change in authselect -> violates packaging guidelines because of some nsswtich hack).

Anyway, I am currently also looking into how nsswitch can be circumvented completely using resolvctl. But it behaves oddly and I might have to open another issue there...

**Comment by pbrezina** [comment]
I don't see the chicken egg problem - unless you try to enable the module automatically in spec file upon rpm installation?

Is there any update on the systemd side?

**Comment by schanzen** [comment]
There is no update on https://github.com/systemd/systemd/issues/24532 as you can see.

I also opened https://github.com/systemd/systemd/issues/25020 because in addition to NSS we also support to intercept DNS queries through a local DNS service. This could be configured in systemd as a resolver. But, the behavior of systemd is (IMO) too, eh, eccentric with respect to fallback DNS servers. Which is why my bug was closed as a duplicate of the old and controversial https://github.com/systemd/systemd/issues/5755.

I do believe that systemd-resolvd is conceptually the right way to do this for systems that use it, but chances this happening are slim to none as it seems.
Note that there is effort in the IETF in order to separate namespaces of alternative name systems and DNS using the .alt special-use TLD: https://datatracker.ietf.org/doc/draft-ietf-dnsop-alt-tld/
So eventually this may be tackled in the future somehow.
The easiest way to do it (for systemd) would be to drop ".alt" names.
But, of course, it would be better (IMO) if alternative name systems could plug into resolvd, hence https://github.com/systemd/systemd/issues/24532

For now, while I see how authselect is a tool modifying nsswitch, do you as a maintainer think that (host)name resolution plugin modification (and thereby messing with resolvd) is something authselect should be doing? If yes, then that may be a path of least resistance.
But it would also be completely reasonable to close this issue here as wontfix.
