### ISSUE TITLE
minimal profile does not support with-homed feature

### ISSUE THREAD

**Issue by DaanDeMeyer** [authselect/authselect#339]
Unlike the other profiles, the with-homed feature was not added to the minimal profile, it'd be great it the minimal profile supported with-homed as well

**Comment by pbrezina** [comment]
Hi, would you be willing to open a pull request for this?

**Comment by pbrezina** [comment]
Nevermind, I opened https://github.com/authselect/authselect/pull/343. It would be great if you can review it.
