### ISSUE TITLE
pam_lastlog.so is gone

### ISSUE THREAD

**Issue by sudipm-mukherjee** [authselect/authselect#374]
authselect references pam_lastlog.so. However, it has been disabled in PAM upstream,

Ref: https://github.com/linux-pam/linux-pam/commit/357a4ddbe9b4b10ebd805d2af3e32f3ead5b8816

**Comment by pbrezina** [comment]
@ikerexxe Hi Iker, what are current plans in Fedora and RHEL?

**Comment by ikerexxe** [comment]
At some point in the future, probably before RHEL11, we'll need to move from pam_lastlog to pam_lastlog2 (provided by util-linux). I still need to sit down with Karel and decide when that will be. Rest assured that you, and the Fedora community, will be duly informed with a System-Wide Change.

If you want to understand the reasons for this change I recommend you read https://github.com/util-linux/util-linux/blob/master/liblastlog2/README.md

**Comment by pbrezina** [comment]
Thank you. I'm closing this for now, please, reopen this issue or create new one as part of the change page.

**Comment by sudipm-mukherjee** [comment]
Then no fix?
I will then remove "authselect" from Debian Trixie release as `pam_lastlog` is not available in Debian.

**Comment by ikerexxe** [comment]
Has Debian already switched from lastlog to lastlog2?

**Comment by pbrezina** [comment]
> Then no fix? I will then remove "authselect" from Debian Trixie release as `pam_lastlog` is not available in Debian.

Hi, there is no need to remove it, just patch it for the time being with downstream only patch. The profiles that are bundled with authselect are Fedora oriented, so it contains what is currently used in Fedora. It is expected that other distributions tinker with them as they need, either by altering the sources or by overwriting them with [vendor-specific profiles](https://github.com/authselect/authselect/wiki/Profiles:-Types#vendor-profiles) .

**Comment by sudipm-mukherjee** [comment]
> Has Debian already switched from lastlog to lastlog2?

pam_lastlog.so is no longer available in Debian and will not be part of the Debian Trixie release.
More details at https://bugs.debian.org/1068017

**Comment by ikerexxe** [comment]
I plan to migrate from lastlog to lastlog2 for Fedora 43. Do you mind reopening this ticket to work on it?

**Comment by pbrezina** [comment]
Sure, keep me posted.
