### ISSUE TITLE
Question: What is the best approach to deploy your pam module?

### ISSUE THREAD

**Issue by lo1ol** [authselect/authselect#381]
Hi!

My team create pam module for working with smart cards, that has some extra features compare to pam_pkcs11.

We distribute it as deb/rpm package with tools to config it. Our first version of this tool updated `/etc/pam.d/` configs directly using regexp's. It works, but we could lose changes if some of the packages decided to update configs. Because of that we thinking about setup pam configs using authselect.

I figured out only one approach for doing it. It's create new profiles based on minimal and sssd profiles and apply a little bit changed regexps for that. It should work, but.

1. We want to update our profiles if one of the base profiles updated
2. Our changes will not be applied if will be used another profile
3. I thing it's not a best approach. For example, for distros with pam-auth-update we just create description how to inject our pam module (lines and priority of this lines) and this should work without any regexps

So, could you suggest the best practices of deploying custom pam modules?

**Comment by pbrezina** [comment]
Hi, I think you got it correctly. There are options:

1. Get it into authselect upstream. I can consider it, but smartcards are already handled by sssd so honestly, it is unlikely.
2. Create custom profile. But this means that you are responsible to upgrade it together with the profiles we ship. So far there is no auto-update with regexp option.

**Comment by pbrezina** [comment]
Closing, feel free to reopen.

**Comment by pbrezina** [comment]
For what it's worth, the profiles, that are included in authselect upstream are Fedora/RHEL oriented. It is expected that other distributions will ship their own profiles. So it does not have to go to upstream, but can be managed by Debian maintainer, for example. There is currently an issue where pam_lastlog is still used by Fedora but already not included in Debian: https://github.com/authselect/authselect/issues/374 

It is also possible to ship "[vendor](https://github.com/authselect/authselect/wiki/Profiles:-Types#vendor-profiles)" profiles in custom debian or rpm package.

But of course, the maintenance burden goes to you or the distro maintainer either way..
