### ISSUE TITLE
[dist] authselect should own nsswitch  in Fedora

### ISSUE THREAD

**Issue by jhrozek** [authselect/authselect#9]
I'm not sure if this belongs to the upstream project, but I think we should work with the Fedora glibc maintainers and make authselect own the nsswitch.conf file instead of glibc.

**Comment by pbrezina** [comment]
This is a good idea and it should be considered for F29.

**Comment by jhrozek** [comment]
I would argue that if we want to do this, the change should happen sooner or later.

But what we can do already is send a mail to Florian Weimer and Carlos O'Donnel. I would specifically like to know their opinion on this change in light of containers which are generally very light-weight and if nsswitch was owned by authselect, would we need to include authselect in the minimal container images?

**Comment by sgallagher** [comment]
In that case, I think what I'd do is make nsswitch a subpackage of authselect that authselect has a hard dependency on. Then we can have glibc, autofs, sudo, etc. add a dep on that.

**Comment by sgallagher** [comment]
(Obviously, we'd have to have a reasonable default for the container case; if that's not possible, a full dependency on authselect is the only sensible option)

**Comment by pbrezina** [comment]
We are past F29 changes deadline but I think it is ok since authselect can be better adopted by community during F28 and F29 releases. Changes proposal deadline for F30 is Jan 8 2019, we must have a reasonable plan in that time.

**Comment by q2dg** [comment]
So...what happened with this finally?

**Comment by pbrezina** [comment]
So far no work or discussion with glibc has been done. There were still some bugs and rfe's around authselect that I wanted to fix to make sure it is stable enough to do this change.

**Comment by pbrezina** [comment]
Related to [Fedora 36 Change Page: Enforce Authselect Configuration Consistency](https://fedoraproject.org/wiki/Changes/Make_Authselect_Mandatory)
